using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "InitialSpellData<Int32>"/>
	/// </summary>
	public sealed partial class InitialSpellData_Int32_Serializer : BaseAutoGeneratedSerializerStrategy<InitialSpellData_Int32_Serializer, InitialSpellData<Int32>>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(InitialSpellData<Int32> value, Span<byte> buffer, ref int offset)
		{
			//Type: InitialSpellData Field: 1 Name: SpellId Type: Int32
			;
			value.SpellId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
			//Type: InitialSpellData Field: 2 Name: UnkShort Type: Int16
			;
			value.UnkShort = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(InitialSpellData<Int32> value, Span<byte> buffer, ref int offset)
		{
			//Type: InitialSpellData Field: 1 Name: SpellId Type: Int32
			;
			GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellId, buffer, ref offset);
			//Type: InitialSpellData Field: 2 Name: UnkShort Type: Int16
			;
			GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.UnkShort, buffer, ref offset);
		}
	}
}