using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.CustomTypes;

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="OpenGenericVector<Byte>"/>
    /// </summary>
    public sealed partial class OpenGenericVector_Byte_Serializer
            : BaseAutoGeneratedSerializerStrategy<OpenGenericVector_Byte_Serializer, OpenGenericVector<Byte>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(OpenGenericVector<Byte> value, Span<byte> buffer, ref int offset)
        {
            //Type: OpenGenericVector Field: 1 Name: Value1 Type: Byte;
            value.Value1 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: OpenGenericVector Field: 2 Name: Value2 Type: Byte;
            value.Value2 = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(OpenGenericVector<Byte> value, Span<byte> buffer, ref int offset)
        {
            //Type: OpenGenericVector Field: 1 Name: Value1 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.Value1, buffer, ref offset);
            //Type: OpenGenericVector Field: 2 Name: Value2 Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.Value2, buffer, ref offset);
        }
    }
}