using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serialization.Tests.RealWorld;

namespace FreecraftCore.Serialization.Tests.RealWorld
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class PatchingWelcomePayload
	{
		public override Type SerializableType => typeof(PatchingWelcomePayload);
		public override PSOBBPatchPacketPayloadServer Read(Span<byte> buffer, ref int offset)
		{
			PatchingWelcomePayload_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public override void Write(PSOBBPatchPacketPayloadServer value, Span<byte> buffer, ref int offset)
		{
			PatchingWelcomePayload_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serialization.Tests.RealWorld
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "PatchingWelcomePayload"/>
	/// </summary>
	public sealed partial class PatchingWelcomePayload_Serializer : BaseAutoGeneratedSerializerStrategy<PatchingWelcomePayload_Serializer, PatchingWelcomePayload>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(PatchingWelcomePayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: UInt16
			;
			value.OperationCode = GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 1 Name: PatchCopyrightMessage Type: String
			;
			value.PatchCopyrightMessage = FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_44>.Instance.Read(buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 2 Name: Padding Type: Byte[]
			;
			value.Padding = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_20>.Instance.Read(buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 3 Name: ServerVector Type: UInt32
			;
			value.ServerVector = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 4 Name: ClientVector Type: UInt32
			;
			value.ClientVector = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(PatchingWelcomePayload value, Span<byte> buffer, ref int offset)
		{
			//Type: PSOBBPatchPacketPayloadServer Field: 1 Name: OperationCode Type: UInt16
			;
			GenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 1 Name: PatchCopyrightMessage Type: String
			;
			FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_44>.Instance.Write(value.PatchCopyrightMessage, buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 2 Name: Padding Type: Byte[]
			;
			FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_20>.Instance.Write(value.Padding, buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 3 Name: ServerVector Type: UInt32
			;
			GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.ServerVector, buffer, ref offset);
			//Type: PatchingWelcomePayload Field: 4 Name: ClientVector Type: UInt32
			;
			GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.ClientVector, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_44 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 44;
		}

		private sealed class StaticTypedNumeric_Int32_20 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 20;
		}
	}
}