using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.CustomTypes;

namespace FreecraftCore.Serializer.CustomTypes
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "PrimitiveGenericTypeStub<Int64>"/>
	/// </summary>
	public sealed partial class PrimitiveGenericTypeStub_Int64_Serializer : BaseAutoGeneratedSerializerStrategy<PrimitiveGenericTypeStub_Int64_Serializer, PrimitiveGenericTypeStub<Int64>>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(PrimitiveGenericTypeStub<Int64> value, Span<byte> buffer, ref int offset)
		{
			//Type: PrimitiveGenericTypeStub Field: 1 Name: Value Type: Int64
			;
			value.Value = GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(PrimitiveGenericTypeStub<Int64> value, Span<byte> buffer, ref int offset)
		{
			//Type: PrimitiveGenericTypeStub Field: 1 Name: Value Type: Int64
			;
			GenericTypePrimitiveSerializerStrategy<Int64>.Instance.Write(value.Value, buffer, ref offset);
		}
	}
}