using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serialization.Tests.RealWorld;

namespace FreecraftCore.Serialization.Tests.RealWorld
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class TestModel : IWireMessage<TestModel>
	{
		public Type SerializableType => typeof(TestModel);
		public TestModel Read(Span<byte> buffer, ref int offset)
		{
			TestModel_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public void Write(TestModel value, Span<byte> buffer, ref int offset)
		{
			TestModel_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "TestModel"/>
	/// </summary>
	public sealed partial class TestModel_Serializer : BaseAutoGeneratedSerializerStrategy<TestModel_Serializer, TestModel>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(TestModel value, Span<byte> buffer, ref int offset)
		{
			//Type: TestModel Field: 1 Name: TestEnumField Type: TestEnum
			;
			value.TestEnumField = InternalEnumExtensions.Parse<TestEnum>(FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_4, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset), true);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(TestModel value, Span<byte> buffer, ref int offset)
		{
			//Type: TestModel Field: 1 Name: TestEnumField Type: TestEnum
			;
			FixedSizeStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, StaticTypedNumeric_Int32_4, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.TestEnumField, buffer, ref offset);
		}

		private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32>
		{
			public sealed override Int32 Value => 4;
		}
	}
}