using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.CustomTypes;

namespace FreecraftCore.Serializer.CustomTypes
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class BaseTypeStub : IWireMessage<BaseTypeStub>
    {
        public Type SerializableType => typeof(BaseTypeStub);
        public BaseTypeStub Read(Span<byte> buffer, ref int offset)
        {
            BaseTypeStub_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public void Write(BaseTypeStub value, Span<byte> buffer, ref int offset)
        {
            BaseTypeStub_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BaseTypeStub"/>
    /// </summary>
    public sealed partial class BaseTypeStub_AutoGeneratedTemplateSerializerStrategy
        : BasePolymorphicAutoGeneratedSerializerStrategy<BaseTypeStub_AutoGeneratedTemplateSerializerStrategy, BaseTypeStub, int>
    {
        protected override BaseTypeStub CreateType(int key)
        {
            switch (key)
            {
                case 1:
                    return new TypeStub();
                default:
                    throw new NotImplementedException($"Encountered unimplemented sub-type for Type: {nameof(BaseTypeStub)} with Key: {key}");
            }
        }
    }
}