using System;
using System.Collections.Generic;
using System.Text;

namespace FreecraftCore.Serializer
{
	/// <summary>
	/// If marked on a Type it means that the IWireMessage implementation is auto-implemented
	/// and future generations should not implemented OVERRIDE implementations because the compiler
	/// added them to begin with.
	/// </summary>
	[AttributeUsage(AttributeTargets.Class, Inherited = true)]
	public sealed class AutoGeneratedWireMessageImplementationAttribute : Attribute
	{

	}
}
