using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FreecraftCore
{
	[AttributeUsage(AttributeTargets.Class)]
	public sealed class AutoGeneratedAttribute : Attribute
	{
		public AutoGeneratedAttribute()
		{
			
		}
	}
}
