using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using JetBrains.Annotations;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace FreecraftCore.Serializer
{
	public sealed class PolymorphicSerializerImplementationCompilationUnitEmitter<TSerializableType> : BaseSerializerImplementationCompilationUnitEmitter<TSerializableType>
	{
		private PrimitiveSizeType PolymorphicKeySizeType { get; } = typeof(TSerializableType).GetCustomAttribute<WireDataContractAttribute>().OptionalSubTypeKeySize.Value;

		protected override MemberDeclarationSyntax CreateSerializerImplementationNamespaceMember()
		{
			return NamespaceDeclaration
				(
					QualifiedName
					(
						IdentifierName("FreecraftCore"),
						IdentifierName
						(
							Identifier
							(
								TriviaList(),
								"Serializer",
								TriviaList
								(
									CarriageReturnLineFeed
								)
							)
						)
					)
				)
				.WithNamespaceKeyword
				(
					Token
					(
						TriviaList(),
						SyntaxKind.NamespaceKeyword,
						TriviaList
						(
							Space
						)
					)
				)
				.WithOpenBraceToken
				(
					Token
					(
						TriviaList(),
						SyntaxKind.OpenBraceToken,
						TriviaList
						(
							CarriageReturnLineFeed
						)
					)
				)
				.WithMembers
				(
					SingletonList<MemberDeclarationSyntax>
					(
						ClassDeclaration
							(
								Identifier
								(
									TriviaList(),
									SerializerTypeName,
									TriviaList
									(
										new[]
										{
											Space,
											CarriageReturnLineFeed
										}
									)
								)
							)
							.WithModifiers
							(
								TokenList
								(
									new[]
									{
										Token
										(
											TriviaList
											(
												new[]
												{
													Tab,
													Comment("//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!"),
													CarriageReturnLineFeed,
													Tab,
													Trivia
													(
														DocumentationCommentTrivia
														(
															SyntaxKind.SingleLineDocumentationCommentTrivia,
															List<XmlNodeSyntax>
															(
																new XmlNodeSyntax[]
																{
																	XmlText()
																		.WithTextTokens
																		(
																			TokenList
																			(
																				XmlTextLiteral
																				(
																					TriviaList
																					(
																						DocumentationCommentExterior("///")
																					),
																					" ",
																					" ",
																					TriviaList()
																				)
																			)
																		),
																	XmlExampleElement
																		(
																			XmlText()
																				.WithTextTokens
																				(
																					TokenList
																					(
																						new[]
																						{
																							XmlTextNewLine
																							(
																								TriviaList(),
																								Environment.NewLine,
																								Environment.NewLine,
																								TriviaList()
																							),
																							XmlTextLiteral
																							(
																								TriviaList
																								(
																									DocumentationCommentExterior("	///")
																								),
																								" FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization",
																								" FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization",
																								TriviaList()
																							),
																							XmlTextNewLine
																							(
																								TriviaList(),
																								Environment.NewLine,
																								Environment.NewLine,
																								TriviaList()
																							),
																							XmlTextLiteral
																							(
																								TriviaList
																								(
																									DocumentationCommentExterior("	///")
																								),
																								" code for the Type: ",
																								" code for the Type: ",
																								TriviaList()
																							)
																						}
																					)
																				),
																			XmlNullKeywordElement()
																				.WithAttributes
																				(
																					SingletonList<XmlAttributeSyntax>
																					(
																						XmlCrefAttribute
																						(
																							NameMemberCref
																							(
																								IdentifierName(SerializableTypeName)
																							)
																						)
																					)
																				),
																			XmlText()
																				.WithTextTokens
																				(
																					TokenList
																					(
																						new[]
																						{
																							XmlTextNewLine
																							(
																								TriviaList(),
																								Environment.NewLine,
																								Environment.NewLine,
																								TriviaList()
																							),
																							XmlTextLiteral
																							(
																								TriviaList
																								(
																									DocumentationCommentExterior("	///")
																								),
																								" ",
																								" ",
																								TriviaList()
																							)
																						}
																					)
																				)
																		)
																		.WithStartTag
																		(
																			XmlElementStartTag
																			(
																				XmlName
																				(
																					Identifier("summary")
																				)
																			)
																		)
																		.WithEndTag
																		(
																			XmlElementEndTag
																			(
																				XmlName
																				(
																					Identifier("summary")
																				)
																			)
																		),
																	XmlText()
																		.WithTextTokens
																		(
																			TokenList
																			(
																				XmlTextNewLine
																				(
																					TriviaList(),
																					Environment.NewLine,
																					Environment.NewLine,
																					TriviaList()
																				)
																			)
																		)
																}
															)
														)
													),
													Tab
												}
											),
											SyntaxKind.PublicKeyword,
											TriviaList
											(
												Space
											)
										),
										Token
										(
											TriviaList(),
											SyntaxKind.SealedKeyword,
											TriviaList
											(
												Space
											)
										),
										Token
										(
											TriviaList(),
											SyntaxKind.PartialKeyword,
											TriviaList
											(
												Space
											)
										)
									}
								)
							)
							.WithKeyword
							(
								Token
								(
									TriviaList(),
									SyntaxKind.ClassKeyword,
									TriviaList
									(
										Space
									)
								)
							)
							.WithBaseList
							(
								BaseList
									(
										SingletonSeparatedList<BaseTypeSyntax>
										(
											SimpleBaseType
											(
												GenericName
													(
														Identifier("BasePolymorphicAutoGeneratedSerializerStrategy")
													)
													.WithTypeArgumentList
													(
														TypeArgumentList
															(
																SeparatedList<TypeSyntax>
																(
																	new SyntaxNodeOrToken[]
																	{
																		IdentifierName(SerializerTypeName),
																		Token
																		(
																			TriviaList(),
																			SyntaxKind.CommaToken,
																			TriviaList
																			(
																				Space
																			)
																		),
																		IdentifierName(SerializableTypeName),
																		Token
																		(
																			TriviaList(),
																			SyntaxKind.CommaToken,
																			TriviaList
																			(
																				Space
																			)
																		),
																		IdentifierName(PolymorphicKeySizeType.ToString())
																	}
																)
															)
															.WithGreaterThanToken
															(
																Token
																(
																	TriviaList(),
																	SyntaxKind.GreaterThanToken,
																	TriviaList
																	(
																		CarriageReturnLineFeed
																	)
																)
															)
													)
											)
										)
									)
									.WithColonToken
									(
										Token
										(
											TriviaList
											(
												Whitespace("		")
											),
											SyntaxKind.ColonToken,
											TriviaList
											(
												Space
											)
										)
									)
							)
							.WithOpenBraceToken
							(
								Token
								(
									TriviaList
									(
										Tab
									),
									SyntaxKind.OpenBraceToken,
									TriviaList
									(
										CarriageReturnLineFeed
									)
								)
							)
							.WithMembers
							(
								SingletonList<MemberDeclarationSyntax>
								(
									MethodDeclaration
										(
											IdentifierName
											(
												Identifier
												(
													TriviaList(),
													SerializableTypeName,
													TriviaList
													(
														Space
													)
												)
											),
											Identifier("CreateType")
										)
										.WithModifiers
										(
											TokenList
											(
												new[]
												{
													Token
													(
														TriviaList
														(
															Whitespace("		")
														),
														SyntaxKind.ProtectedKeyword,
														TriviaList
														(
															Space
														)
													),
													Token
													(
														TriviaList(),
														SyntaxKind.OverrideKeyword,
														TriviaList
														(
															Space
														)
													)
												}
											)
										)
										.WithParameterList
										(
											ParameterList
												(
													SingletonSeparatedList<ParameterSyntax>
													(
														Parameter
															(
																Identifier("key")
															)
															.WithType
															(
																PredefinedType
																(
																	Token
																	(
																		TriviaList(),
																		SyntaxKind.IntKeyword,
																		TriviaList
																		(
																			Space
																		)
																	)
																)
															)
													)
												)
												.WithCloseParenToken
												(
													Token
													(
														TriviaList(),
														SyntaxKind.CloseParenToken,
														TriviaList
														(
															CarriageReturnLineFeed
														)
													)
												)
										)
										.WithBody
										(
											Block
												(
													SingletonList<StatementSyntax>
													(
														SwitchStatement
															(
																IdentifierName("key")
															)
															.WithSwitchKeyword
															(
																Token
																(
																	TriviaList
																	(
																		Whitespace("			")
																	),
																	SyntaxKind.SwitchKeyword,
																	TriviaList
																	(
																		Space
																	)
																)
															)
															.WithCloseParenToken
															(
																Token
																(
																	TriviaList(),
																	SyntaxKind.CloseParenToken,
																	TriviaList
																	(
																		CarriageReturnLineFeed
																	)
																)
															)
															.WithOpenBraceToken
															(
																Token
																(
																	TriviaList
																	(
																		Whitespace("			")
																	),
																	SyntaxKind.OpenBraceToken,
																	TriviaList
																	(
																		CarriageReturnLineFeed
																	)
																)
															)
															.WithSections
															(
																List<SwitchSectionSyntax>
																(
																	BuildSwitchStatements()
																)
															)
															.WithCloseBraceToken
															(
																Token
																(
																	TriviaList
																	(
																		Whitespace("			")
																	),
																	SyntaxKind.CloseBraceToken,
																	TriviaList
																	(
																		CarriageReturnLineFeed
																	)
																)
															)
													)
												)
												.WithOpenBraceToken
												(
													Token
													(
														TriviaList
														(
															Whitespace("		")
														),
														SyntaxKind.OpenBraceToken,
														TriviaList
														(
															CarriageReturnLineFeed
														)
													)
												)
												.WithCloseBraceToken
												(
													Token
													(
														TriviaList
														(
															Whitespace("		")
														),
														SyntaxKind.CloseBraceToken,
														TriviaList
														(
															CarriageReturnLineFeed
														)
													)
												)
										)
								)
							)
							.WithCloseBraceToken
							(
								Token
								(
									TriviaList
									(
										Tab
									),
									SyntaxKind.CloseBraceToken,
									TriviaList
									(
										CarriageReturnLineFeed
									)
								)
							)
					)
				)
				.WithCloseBraceToken
				(
					Token
					(
						TriviaList(),
						SyntaxKind.CloseBraceToken,
						TriviaList
						(
							CarriageReturnLineFeed
						)
					)
				);
		}

		private IEnumerable<SwitchSectionSyntax> BuildSwitchStatements()
		{
			//Every type that is a child type in the same assembly
			foreach (PolymorphicTypeInfo typeInfo in GetPolymorphicChildTypes())
			{
				yield return SwitchSection()
					.WithLabels
					(
						SingletonList<SwitchLabelSyntax>
						(
							CaseSwitchLabel
								(
									LiteralExpression
									(
										SyntaxKind.NumericLiteralExpression,
										Literal(typeInfo.Index)
									)
								)
								.WithKeyword
								(
									Token
									(
										TriviaList
										(
											Whitespace("				")
										),
										SyntaxKind.CaseKeyword,
										TriviaList
										(
											Space
										)
									)
								)
								.WithColonToken
								(
									Token
									(
										TriviaList(),
										SyntaxKind.ColonToken,
										TriviaList
										(
											CarriageReturnLineFeed
										)
									)
								)
						)
					)
					.WithStatements
					(
						SingletonList<StatementSyntax>
						(
							ReturnStatement
								(
									ObjectCreationExpression
										(
											CreateChildTypeIdentifier(typeInfo.ChildType)
										)
										.WithNewKeyword
										(
											Token
											(
												TriviaList(),
												SyntaxKind.NewKeyword,
												TriviaList
												(
													Space
												)
											)
										)
										.WithArgumentList
										(
											ArgumentList()
										)
								)
								.WithReturnKeyword
								(
									Token
									(
										TriviaList
										(
											Whitespace("					")
										),
										SyntaxKind.ReturnKeyword,
										TriviaList
										(
											Space
										)
									)
								)
								.WithSemicolonToken
								(
									Token
									(
										TriviaList(),
										SyntaxKind.SemicolonToken,
										TriviaList
										(
											CarriageReturnLineFeed
										)
									)
								)
						)
					);
			}

			DefaultChildAttribute defaultChildAttribute = typeof(TSerializableType).GetCustomAttribute<DefaultChildAttribute>();

			if (defaultChildAttribute != null)
			{
				yield return SwitchSection()
					.WithLabels
					(
						SingletonList<SwitchLabelSyntax>
						(
							DefaultSwitchLabel()
								.WithKeyword
								(
									Token
									(
										TriviaList
										(
											Whitespace("				")
										),
										SyntaxKind.DefaultKeyword,
										TriviaList()
									)
								)
								.WithColonToken
								(
									Token
									(
										TriviaList(),
										SyntaxKind.ColonToken,
										TriviaList
										(
											CarriageReturnLineFeed
										)
									)
								)
						)
					)
					.WithStatements
					(
						SingletonList<StatementSyntax>
						(
							ReturnStatement
								(
									ObjectCreationExpression
										(
											IdentifierName(defaultChildAttribute.ChildType.FullName)
										)
										.WithNewKeyword
										(
											Token
											(
												TriviaList(),
												SyntaxKind.NewKeyword,
												TriviaList
												(
													Space
												)
											)
										)
										.WithArgumentList
										(
											ArgumentList()
										)
								)
								.WithReturnKeyword
								(
									Token
									(
										TriviaList
										(
											Whitespace("					")
										),
										SyntaxKind.ReturnKeyword,
										TriviaList
										(
											Space
										)
									)
								)
								.WithSemicolonToken
								(
									Token
									(
										TriviaList(),
										SyntaxKind.SemicolonToken,
										TriviaList
										(
											CarriageReturnLineFeed
										)
									)
								)
						)
					);
			}
			else
			{
				yield return SwitchSection()
					.WithLabels
					(
						SingletonList<SwitchLabelSyntax>
						(
							DefaultSwitchLabel()
								.WithKeyword
								(
									Token
									(
										TriviaList
										(
											Whitespace("				")
										),
										SyntaxKind.DefaultKeyword,
										TriviaList()
									)
								)
								.WithColonToken
								(
									Token
									(
										TriviaList(),
										SyntaxKind.ColonToken,
										TriviaList
										(
											CarriageReturnLineFeed
										)
									)
								)
						)
					)
					.WithStatements
					(
						SingletonList<StatementSyntax>
						(
							ThrowStatement
							(
								ObjectCreationExpression
								(
									IdentifierName(nameof(NotImplementedException))
								)
								.WithNewKeyword
								(
									Token
									(
										TriviaList(),
										SyntaxKind.NewKeyword,
										TriviaList
										(
											Space
										)
									)
								)
								.WithArgumentList
								(
									ArgumentList
									(
										SingletonSeparatedList<ArgumentSyntax>
										(
											Argument
											(
												InterpolatedStringExpression
												(
													Token(SyntaxKind.InterpolatedStringStartToken)
												)
												.WithContents
												(
													List<InterpolatedStringContentSyntax>
													(
														new InterpolatedStringContentSyntax[]
														{
															InterpolatedStringText()
															.WithTextToken
															(
																Token
																(
																	TriviaList(),
																	SyntaxKind.InterpolatedStringTextToken,
																	"Encountered unimplemented sub-type for Type: ",
																	"Encountered unimplemented sub-type for Type: ",
																	TriviaList()
																)
															),
															Interpolation
															(
																InvocationExpression
																(
																	IdentifierName("nameof")
																)
																.WithArgumentList
																(
																	ArgumentList
																	(
																		SingletonSeparatedList<ArgumentSyntax>
																		(
																			Argument
																			(
																				IdentifierName(SerializableTypeName)
																			)
																		)
																	)
																)
															),
															InterpolatedStringText()
															.WithTextToken
															(
																Token
																(
																	TriviaList(),
																	SyntaxKind.InterpolatedStringTextToken,
																	" with Key: ",
																	" with Key: ",
																	TriviaList()
																)
															),
															Interpolation
															(
																IdentifierName("key")
															)
														}
													)
												)
											)
										)
									)
								)
							)
							.WithThrowKeyword
							(
								Token
								(
									TriviaList(),
									SyntaxKind.ThrowKeyword,
									TriviaList
									(
										Space
									)
								)
							)
						)
					);
			}
		}

		private static IEnumerable<PolymorphicTypeInfo> GetPolymorphicChildTypes()
		{
			//Gets child types with link attribute
			//and also types that are directly defined as attributed on the base type itself.
			return typeof(TSerializableType)
				.Assembly
				.GetExportedTypes()
				.Where(t => typeof(TSerializableType).IsAssignableFrom(t))
				.Where(t => t.GetCustomAttribute<WireDataContractAttribute>() != null && t.GetCustomAttribute<WireDataContractBaseLinkAttribute>() != null)
				.Select(t =>
				{
					WireDataContractBaseLinkAttribute attribute = t.GetCustomAttribute<WireDataContractBaseLinkAttribute>();
					return new PolymorphicTypeInfo(attribute.Index, t);
				})
				.Concat(typeof(TSerializableType).GetCustomAttributes<WireDataContractBaseTypeAttribute>().Select(a =>
				{
					return new PolymorphicTypeInfo(a.Index, a.ChildType);
				}))
				.Distinct();
		}

		private static IdentifierNameSyntax CreateChildTypeIdentifier([NotNull] Type childType)
		{
			if (childType == null) throw new ArgumentNullException(nameof(childType));

			string baseTypeNameSpace = typeof(TSerializableType).Namespace;

			if (childType.Namespace == null || baseTypeNameSpace == null)
				return IdentifierName(childType.FullName);

			return childType.Namespace.StartsWith(baseTypeNameSpace) ? IdentifierName(childType.Name) : IdentifierName(childType.FullName);
		}
	}
}
