using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.CustomTypes;
namespace FreecraftCore.Serializer.CustomTypes
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class BaseEnumWireContractTestType : IWireMessage<BaseEnumWireContractTestType>
    {
        public virtual Type SerializableType => typeof(BaseEnumWireContractTestType);
        public virtual BaseEnumWireContractTestType Read(Span<byte> buffer, ref int offset)
        {
            BaseEnumWireContractTestType_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(BaseEnumWireContractTestType value, Span<byte> buffer, ref int offset)
        {
            BaseEnumWireContractTestType_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BaseEnumWireContractTestType"/>
    /// </summary>
    public sealed partial class BaseEnumWireContractTestType_AutoGeneratedTemplateSerializerStrategy
        : BasePolymorphicAutoGeneratedSerializerStrategy<BaseEnumWireContractTestType_AutoGeneratedTemplateSerializerStrategy, BaseEnumWireContractTestType, Int32>
    {
        protected override BaseEnumWireContractTestType CreateType(int key)
        {
            switch (key)
            {
                case (int)FreecraftCore.Serializer.CustomTypes.BaseEnumType.Test1:
                    return new ChildEnumWireContractTestType();
                default:
                    throw new NotImplementedException($"Encountered unimplemented sub-type for Type: {nameof(BaseEnumWireContractTestType)} with Key: {key}");
            }
        }
    }
}