using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.CustomTypes;
namespace FreecraftCore.Serializer.CustomTypes
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class BaseTypeStub : IWireMessage<BaseTypeStub>
    {
        public virtual Type SerializableType => typeof(BaseTypeStub);
        public virtual BaseTypeStub Read(Span<byte> buffer, ref int offset)
        {
            BaseTypeStub.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(BaseTypeStub value, Span<byte> buffer, ref int offset)
        {
            BaseTypeStub.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="BaseTypeStub"/>
    /// </summary>
    public sealed partial class BaseTypeStub
            : BasePolymorphicAutoGeneratedSerializerStrategy<BaseTypeStub, BaseTypeStub, UInt16>
    {
        protected override BaseTypeStub CreateType(int key)
        {
            switch (key)
            {
                case 1:
                    return new TypeStub();
                case 2:
                    return new TypeStub2();
                default:
                    throw new NotImplementedException($"Encountered unimplemented sub-type for Type: {nameof(BaseTypeStub)} with Key: {key}");
            }
        }
    }
}