using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="InitialSpellCooldown<Int32>"/>
    /// </summary>
    public sealed partial class InitialSpellCooldown_Int32_Serializer
            : BaseAutoGeneratedSerializerStrategy<InitialSpellCooldown_Int32_Serializer, InitialSpellCooldown<Int32>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(InitialSpellCooldown<Int32> value, Span<byte> buffer, ref int offset)
        {
            //Type: InitialSpellCooldown Field: 1 Name: SpellId Type: Int32;
            value.SpellId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: InitialSpellCooldown Field: 2 Name: ItemId Type: Int16;
            value.ItemId = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
            //Type: InitialSpellCooldown Field: 3 Name: CategoryId Type: Int16;
            value.CategoryId = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
            //Type: InitialSpellCooldown Field: 4 Name: SpellCooldown Type: UInt32;
            value.SpellCooldown = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: InitialSpellCooldown Field: 5 Name: CategoryCooldown Type: UInt32;
            value.CategoryCooldown = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(InitialSpellCooldown<Int32> value, Span<byte> buffer, ref int offset)
        {
            //Type: InitialSpellCooldown Field: 1 Name: SpellId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellId, buffer, ref offset);
            //Type: InitialSpellCooldown Field: 2 Name: ItemId Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.ItemId, buffer, ref offset);
            //Type: InitialSpellCooldown Field: 3 Name: CategoryId Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.CategoryId, buffer, ref offset);
            //Type: InitialSpellCooldown Field: 4 Name: SpellCooldown Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellCooldown, buffer, ref offset);
            //Type: InitialSpellCooldown Field: 5 Name: CategoryCooldown Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.CategoryCooldown, buffer, ref offset);
        }
    }
}