using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serialization.Tests.RealWorld;
namespace FreecraftCore.Serialization.Tests.RealWorld
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class PSOBBPatchPacketPayloadServer : IWireMessage<PSOBBPatchPacketPayloadServer>
    {
        public virtual Type SerializableType => typeof(PSOBBPatchPacketPayloadServer);
        public virtual PSOBBPatchPacketPayloadServer Read(Span<byte> buffer, ref int offset)
        {
            PSOBBPatchPacketPayloadServer_Serializer.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(PSOBBPatchPacketPayloadServer value, Span<byte> buffer, ref int offset)
        {
            PSOBBPatchPacketPayloadServer_Serializer.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="PSOBBPatchPacketPayloadServer"/>
    /// </summary>
    public sealed partial class PSOBBPatchPacketPayloadServer_Serializer
            : BasePolymorphicAutoGeneratedSerializerStrategy<PSOBBPatchPacketPayloadServer_Serializer, PSOBBPatchPacketPayloadServer, UInt16>
    {
        protected override PSOBBPatchPacketPayloadServer CreateType(int key)
        {
            switch (key)
            {
                case 5:
                    return new PatchingInformationPayload();
                case 153:
                    return new PatchingWelcomePayload();
                default:
                    return new UnknownPatchPacket();
            }
        }
    }
}