using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_INITIAL_SPELLS_Payload : IWireMessage<SMSG_INITIAL_SPELLS_Payload>
    {
        public Type SerializableType => typeof(SMSG_INITIAL_SPELLS_Payload);
        public SMSG_INITIAL_SPELLS_Payload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_INITIAL_SPELLS_Payload.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public void Write(SMSG_INITIAL_SPELLS_Payload value, Span<byte> buffer, ref int offset)
        {
            SMSG_INITIAL_SPELLS_Payload.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_INITIAL_SPELLS_Payload"/>
    /// </summary>
    public sealed partial class SMSG_INITIAL_SPELLS_Payload
            : BaseAutoGeneratedSerializerStrategy<SMSG_INITIAL_SPELLS_Payload, SMSG_INITIAL_SPELLS_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_INITIAL_SPELLS_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: SMSG_INITIAL_SPELLS_Payload Field: 1 Name: Data Type: InitialSpellDataBlock;
            value.Data = InitialSpellDataBlock_Int32.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_INITIAL_SPELLS_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: SMSG_INITIAL_SPELLS_Payload Field: 1 Name: Data Type: InitialSpellDataBlock;
            InitialSpellDataBlock_Int32.Instance.Write(value.Data, buffer, ref offset);
        }
    }
}