using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;

namespace FreecraftCore.Serializer
{
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref="TypeStub"/>
	/// </summary>
	internal sealed partial class AutoGeneratedTemplateSerializerStrategy 
		: BaseAutoGeneratedSerializerStrategy<AutoGeneratedTemplateSerializerStrategy, TypeStub>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name="value">See external doc.</param>
		/// <param name="source">See external doc.</param>
		/// <param name="offset">See external doc.</param>
		partial void GeneratedRead(TypeStub value, Span<byte> source, ref int offset)
		{
			throw new NotImplementedException();
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name="value">See external doc.</param>
		/// <param name="destination">See external doc.</param>
		/// <param name="offset">See external doc.</param>
		partial void GeneratedWrite(TypeStub value, Span<byte> destination, ref int offset)
		{
			throw new NotImplementedException();
		}
	}
}
