using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;

namespace FreecraftCore.Serializer
{
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref="TypeStub"/>
	/// </summary>
	internal sealed class AutoGeneratedTemplateSerializerStrategy 
		: BaseAutoGeneratedSerializerStrategy<AutoGeneratedTemplateSerializerStrategy, TypeStub>
	{
		protected override void InternalRead(TypeStub value, Span<byte> source, ref int offset)
		{
			throw new NotImplementedException();
		}

		protected override void InternalWrite(TypeStub value, Span<byte> destination, ref int offset)
		{
			throw new NotImplementedException();
		}
	}
}
