using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;

namespace FreecraftCore.Serializer
{
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref="TypeStub"/>
	/// </summary>
	public sealed partial class PolymorphicAutoGeneratedTemplateSerializerStrategy 
		: BasePolymorphicAutoGeneratedSerializerStrategy<PolymorphicAutoGeneratedTemplateSerializerStrategy, TypeStub, int>
	{
		protected override TypeStub CreateType(int key)
		{
			switch (key)
			{
				case 1:
					return new TypeStub();
				case 2:
					return new TypeStub();
				default:
					return null;
			}
		}
	}
}
