using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.Perf;

namespace FreecraftCore.Serializer.Perf
{
	[AutoGeneratedWireMessageImplementationAttribute]
	public partial class LogonProofFailure
	{
		public override Type SerializableType => typeof(LogonProofFailure);
		public override BaseLogonProofResult Read(Span<byte> buffer, ref int offset)
		{
			LogonProofFailure_Serializer.Instance.InternalRead(this, buffer, ref offset);
			return this;
		}

		public override void Write(BaseLogonProofResult value, Span<byte> buffer, ref int offset)
		{
			LogonProofFailure_Serializer.Instance.InternalWrite(this, buffer, ref offset);
		}
	}
}

namespace FreecraftCore.Serializer
{
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	//THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
	/// <summary>
	/// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
	/// code for the Type: <see cref = "LogonProofFailure"/>
	/// </summary>
	public sealed partial class LogonProofFailure_Serializer : BaseAutoGeneratedSerializerStrategy<LogonProofFailure_Serializer, LogonProofFailure>
	{
		/// <summary>
		/// Auto-generated deserialization/read method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalRead(LogonProofFailure value, Span<byte> buffer, ref int offset)
		{
			//Type: BaseLogonProofResult Field: 1 Name: Result Type: AuthenticationResult
			;
			value.Result = GenericPrimitiveEnumTypeSerializerStrategy<AuthenticationResult, Byte>.Instance.Read(buffer, ref offset);
			//Type: LogonProofFailure Field: 1 Name: UnknownOne Type: Byte
			;
			value.UnknownOne = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
			//Type: LogonProofFailure Field: 2 Name: UnknownTwo Type: Byte
			;
			value.UnknownTwo = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
		}

		/// <summary>
		/// Auto-generated serialization/write method.
		/// Partial method implemented from shared partial definition.
		/// </summary>
		/// <param name = "value">See external doc.</param>
		/// <param name = "buffer">See external doc.</param>
		/// <param name = "offset">See external doc.</param>
		public override void InternalWrite(LogonProofFailure value, Span<byte> buffer, ref int offset)
		{
			//Type: BaseLogonProofResult Field: 1 Name: Result Type: AuthenticationResult
			;
			GenericPrimitiveEnumTypeSerializerStrategy<AuthenticationResult, Byte>.Instance.Write(value.Result, buffer, ref offset);
			//Type: LogonProofFailure Field: 1 Name: UnknownOne Type: Byte
			;
			BytePrimitiveSerializerStrategy.Instance.Write(value.UnknownOne, buffer, ref offset);
			//Type: LogonProofFailure Field: 2 Name: UnknownTwo Type: Byte
			;
			BytePrimitiveSerializerStrategy.Instance.Write(value.UnknownTwo, buffer, ref offset);
		}
	}
}