using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serializer.Tests;
namespace FreecraftCore.Serializer.Tests
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class AuthLogonProofResponse
    {
        public override Type SerializableType => typeof(AuthLogonProofResponse);
        public override AuthPacketBaseTest Read(Span<byte> buffer, ref int offset)
        {
            AuthLogonProofResponse_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(AuthPacketBaseTest value, Span<byte> buffer, ref int offset)
        {
            AuthLogonProofResponse_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="AuthLogonProofResponse"/>
    /// </summary>
    public sealed partial class AuthLogonProofResponse_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<AuthLogonProofResponse_AutoGeneratedTemplateSerializerStrategy, AuthLogonProofResponse>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(AuthLogonProofResponse value, Span<byte> buffer, ref int offset)
        {
            //Type: AuthPacketBaseTest Field: 1 Name: OperationCode Type: Byte;
            value.OperationCode = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: AuthLogonProofResponse Field: 1 Name: ProofResult Type: BaseLogonProofResult;
            value.ProofResult = BaseLogonProofResult_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(AuthLogonProofResponse value, Span<byte> buffer, ref int offset)
        {
            //Type: AuthPacketBaseTest Field: 1 Name: OperationCode Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: AuthLogonProofResponse Field: 1 Name: ProofResult Type: BaseLogonProofResult;
            BaseLogonProofResult_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ProofResult, buffer, ref offset);
        }
    }
}