using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore.Serialization.Tests.RealWorld;

namespace FreecraftCore.Serialization.Tests.RealWorld
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class PSOBBPacketHeader : IWireMessage<PSOBBPacketHeader>
    {
        public virtual Type SerializableType => typeof(PSOBBPacketHeader);
        public virtual PSOBBPacketHeader Read(Span<byte> buffer, ref int offset)
        {
            PSOBBPacketHeader_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(PSOBBPacketHeader value, Span<byte> buffer, ref int offset)
        {
            PSOBBPacketHeader_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="PSOBBPacketHeader"/>
    /// </summary>
    public sealed partial class PSOBBPacketHeader_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<PSOBBPacketHeader_AutoGeneratedTemplateSerializerStrategy, PSOBBPacketHeader>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(PSOBBPacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBPacketHeader Field: 1 Name: PacketSize Type: Int16;
            value.PacketSize = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(PSOBBPacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: PSOBBPacketHeader Field: 1 Name: PacketSize Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.PacketSize, buffer, ref offset);
        }
    }
}